---
  - name: config zabbix-agent systemd
    template:
      src: ../templates/zabbix-agent.service
      dest: /usr/lib/systemd/system/zabbix-agent.service

  - name: start zabbix-aget 
    systemd:
      name: zabbix-agent
      state: started
      daemon_reload: yes

  - name: config zabbix-agent start up on boot
    systemd:
      name: zabbix-agent
      enabled: yes
      daemon_reload: yes
...