---
 - name: install libaio
   yum:
    name: libaio-devel
    state: present

 - name: install numactl
   yum:
    name: numactl-devel
    state: present

 - name: install perl-Data-Dumper 
   yum:
    name: perl-Data-Dumper 
    state: present

...